name = "cookie_cloud"
main = "src/index.js"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "COOKIE_CLOUD"
id = "xxxxxxxxxxxxxxxxx" # 用户需要替换为真实的KV ID
